/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.listarProduto;
import GUI.listarProduto;
import dados.GenericDAO;
import excecoes.BancoDeDadosException;
import excecoes.NomeNuloException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Fachada;
import negocio.entidades.Produto;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import negocio.colecoes.CadastroVendas;
import negocio.entidades.Cliente;
/**
 *
 * @author DEYVISON
 */
public class FormularioVendas extends javax.swing.JFrame {
 
   private Fachada fachada;
   
   public FormularioVendas() throws NomeNuloException {
        initComponents();
        fachada = new Fachada();
              
   }
  
      
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFielProduto = new javax.swing.JFormattedTextField();
        jButtonBuscaCliente = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldQuant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValorItem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jButtonBuscarProduto = new javax.swing.JButton();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jButtonTabelaProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldtotal = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Vendas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Formulário de Vendas");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Produto Cliente:");

        jTextFieldCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto:");

        jFormattedTextFielProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFielProdutoActionPerformed(evt);
            }
        });

        jButtonBuscaCliente.setText("Tablela Clientes");
        jButtonBuscaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaClienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Quantidade:");

        jLabel4.setText("Valor por item:");

        jLabel5.setText("Data:");

        jButtonBuscarProduto.setText("Buscar");
        jButtonBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarProdutoActionPerformed(evt);
            }
        });

        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jLabelID.setText("ID");

        jButtonTabelaProduto.setText("Tabela Produtos");
        jButtonTabelaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabelaProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel5))
                                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jButtonBuscaCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(jButtonTabelaProduto)))
                        .addContainerGap(194, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBuscarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFielProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarProduto)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFielProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarProduto)
                    .addComponent(jButtonBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldValorItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jButtonBuscaCliente)
                    .addComponent(jButtonTabelaProduto))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jtb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Produto", "Data", "Valor", "Quantidade"
            }
        ));
        jScrollPane2.setViewportView(jtb2);

        jLabel6.setText("Tabela de Pesquisa:");

        jLabel7.setText("Itens da Venda:");

        jLabel8.setText("Valor Total:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jButtonAdd, org.jdesktop.beansbinding.ELProperty.create("${alignmentX}"), jTextFieldtotal, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jTextFieldtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtotalActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Vender");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jButtonAdd)
                                .addGap(66, 66, 66)
                                .addComponent(jButtonCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextFieldtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonCancelar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        setBounds(0, 0, 624, 702);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaClienteActionPerformed
         try{
    ArrayList<Cliente> lista1 = fachada.listarCliente();
    
    String[] colunas = {"cliente_id","nome"};        
    
    Object[][] dados1 = carregarDados2(lista1);        
    
    DefaultTableModel model = new DefaultTableModel(dados1, colunas);        
            
    jTable1.setModel(model);
    
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
     jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
     jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
     //jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
     //jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
     //jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
     
     jTable1.setRowSelectionInterval(0, 0);
     
     
      jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
    } catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
     } catch (NomeNuloException ex) {
           Logger.getLogger(FormularioVendas.class.getName()).log(Level.SEVERE, null, ex);
       }
      
         
            
         
      
     //private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {
         //setVisible(false);
     }
         private Object[][] carregarDados2(ArrayList<Cliente> lista1) {
                 Object[][] dados1 = new Object[lista1.size()][2];
         
        for (int i = 0; i < lista1.size(); i++) {
            dados1[i][0] = lista1.get(i).getCliente_id();
            dados1[i][1] = lista1.get(i).getNome();
            //dados[i][2] = lista.get(i).getCpf();
            //dados[i][3] = lista.get(i).getTelefone();
            //dados[i][4] = lista.get(i).getEndereco();
            //dados[i][5] = lista.get(i).getNumero();
            //dados[i][6] = lista.get(i).getCep();
            //dados[i][7] = lista.get(i).getBairro();
           
        }
         return dados1;
    }//GEN-LAST:event_jButtonBuscaClienteActionPerformed

    private void jTextFieldClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldClienteActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
/*listap c = null; //
       try {
           c = new listap();
       } catch (NomeNuloException ex) {
           Logger.getLogger(FormularioVendas.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        c.setVisible(true); */
        
        jLabelID.setText((jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString());
         
        try {
            
            Cliente ler = fachada.lerCliente(jLabelID.getText());

            jTextFieldCliente.setText(ler.getNome());
          
} 
        catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (NomeNuloException ex) {
             Logger.getLogger(listarProduto.class.getName()).log(Level.SEVERE, null, ex);
         }    
        
        
        
        
        
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarProdutoActionPerformed

        jLabelID.setText((jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString());
         
        try {
            
            Produto ler = fachada.lerProduto(jLabelID.getText());

            jFormattedTextFielProduto.setText(ler.getNome());
            jTextFieldValorItem.setText (Double.toString(ler.getPreco()));
} 
        catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        } catch (NomeNuloException ex) {
             Logger.getLogger(listarProduto.class.getName()).log(Level.SEVERE, null, ex);
         }    
      
    
        
           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarProdutoActionPerformed

    private void jFormattedTextFielProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFielProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFielProdutoActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
       
        try {
         DefaultTableModel val = (DefaultTableModel) jtb2.getModel();
          Object[] dados4 = {jTextFieldCliente.getText(),jFormattedTextFielProduto.getText(), jTextFieldData.getText(),jTextFieldValorItem.getText(),jTextFieldQuant.getText()};
          val.addRow(dados4);
            try {
                fachada.adicionarVenda(jTextFieldData.getText(), jTextFieldCliente.getText(), jFormattedTextFielProduto.getText(),Double.parseDouble(jTextFieldValorItem.getText()), Integer.parseInt(jTextFieldQuant.getText()));
                JOptionPane.showMessageDialog(null, "Venda Inserida com sucesso!");
              //  limparCampos();
                
 
            } catch (NomeNuloException ex) {
                Logger.getLogger(CadastroVendas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), 
                    "ERROr",
                    JOptionPane.ERROR_MESSAGE);
        }
       
       soma();
       jTextFieldData.setText("");
          
          jTextFieldCliente.setText("");
          jFormattedTextFielProduto.setText("");
          
          jTextFieldValorItem.setText("");
          jTextFieldQuant.setText("");
         // Double.parseDouble(jTextFieldtotal.getText())=(Double.parseDouble(jTextFieldValorItem.getText())*Integer.parseInt(jTextFieldQuant.getText()));
          
//jPasswordFieldSenha.setText("");
      /*    
         String Cliente= jTextFieldCliente.getText();
         String Produto= jFormattedTextFielProduto.getText().trim();
         String Data= jTextFieldData.getText().trim();
         String Valor= jTextFieldValorItem.getText().trim();
         String Quantidade= jTextFieldQuant.getText().trim(); 
                 DefaultTableModel val = (DefaultTableModel) jtb2.getModel();
                 val.addRow(new String[]{Cliente,Produto, Data, Valor , Quantidade});
           */
          
          
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonTabelaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabelaProdutoActionPerformed
try{
    ArrayList<Produto> lista2 = fachada.listarProduto();
    
    String[] colunas = {"produto_id","nome","preco","quantidade"};      
    
    Object[][] dados2 = carregarDados3(lista2);        
    
    DefaultTableModel model = new DefaultTableModel(dados2, colunas);        
            
    jTable1.setModel(model);
    
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
     jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
     jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
     //jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
     //jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
     //jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
     
     jTable1.setRowSelectionInterval(0, 0);
     
     
      jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
    } catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
     } catch (NomeNuloException ex) {
           Logger.getLogger(FormularioVendas.class.getName()).log(Level.SEVERE, null, ex);
       }
      
         
            
         
      
     //private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {
         //setVisible(false);
     }
         private Object[][] carregarDados3(ArrayList<Produto> lista2) {
                 Object[][] dados2 = new Object[lista2.size()][4];
         
        for (int i = 0; i < lista2.size(); i++) {
            dados2[i][0] = lista2.get(i).getProduto_id();
            dados2[i][1] = lista2.get(i).getNome();
            dados2[i][2] = lista2.get(i).getPreco();
            dados2[i][3] = lista2.get(i).getQuantidade();;
            //dados[i][4] = lista.get(i).getEndereco();
            //dados[i][5] = lista.get(i).getNumero();
            //dados[i][6] = lista.get(i).getCep();
            //dados[i][7] = lista.get(i).getBairro();
           
        }
         return dados2;
                                               
    }//GEN-LAST:event_jButtonTabelaProdutoActionPerformed

    private void jTextFieldtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtotalActionPerformed

soma();
    }//GEN-LAST:event_jTextFieldtotalActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
       dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
public void soma(){
    double x = Double.parseDouble(jTextFieldValorItem.getText());  
int y = Integer.parseInt(jTextFieldQuant.getText());  
double resultado = x*y;  
jTextFieldtotal.setText(String.valueOf(resultado));  
}
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormularioVendas().setVisible(true);
                } catch (NomeNuloException ex) {
                    Logger.getLogger(FormularioVendas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBuscaCliente;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonBuscarProduto;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonTabelaProduto;
    private javax.swing.JFormattedTextField jFormattedTextFielProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldQuant;
    private javax.swing.JTextField jTextFieldValorItem;
    private javax.swing.JTextField jTextFieldtotal;
    private javax.swing.JTable jtb2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
