/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import excecoes.BancoDeDadosException;
import excecoes.LoginExistenteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import negocio.Fachada;
import negocio.entidades.Usuario;

/**
 *
 * @author DEYVISON
 */
public class listarUsuario extends javax.swing.JFrame {

    private Fachada fachada;
    /**
     * Creates new form listarUsuario
     */
    public listarUsuario() throws LoginExistenteException  {
        initComponents();
        
        fachada = new Fachada();
        
    try{
    ArrayList<Usuario> lista = fachada.listarUsuario();
    
    String[] colunas = {"id","login","senha"};        
    
    Object[][] dados = carregarDados(lista);        
    
    DefaultTableModel model = new DefaultTableModel(dados, colunas);        
            
    jTable1.setModel(model);
    
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
     jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
     jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
     //jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);
     jTable1.setRowSelectionInterval(0, 0);
     
     
      jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
    } catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
     }
      
         }
      
     private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {
         setVisible(false);
     }
         private Object[][] carregarDados(ArrayList<Usuario> lista) {
                 Object[][] dados = new Object[lista.size()][3];
         
         
      
      
         for (int i = 0; i < lista.size(); i++) {
            dados[i][0] = lista.get(i).getId();
            dados[i][1] = lista.get(i).getLogin();
            dados[i][2] = lista.get(i).getSenha();
            
         }
         return dados;
    
         }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Usuario");

        jLabel1.setText("Id:");

        jLabel2.setText("Login:");

        jLabel3.setText("Senha:");

        jLabelID.setText("...");

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelID))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonDeletar)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCancelar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldLogin)
                                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonDeletar))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(411, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        jLabelID.setText((jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString());
         
        try {
            
            Usuario ler = fachada.lerUsuario(jLabelID.getText());

            jTextFieldLogin.setText(ler.getLogin());
            //jPasswordFieldSenha.setText (Integer.toString(ler.getSenha()));
             jPasswordFieldSenha.setText(ler.getSenha());
            //jTextFielQuant.setText(Integer.toString(ler.getQuantidade()));
} 
        catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try{
           
           
           //fachada.adicionarUsuarios(jTextFieldCadastroRH.getText(), jTextFieldNome.getText(), jTextFieldCPF.getText(), jTextFieldDataNascimento.getText(), jTextFieldSetor.getText(), String.valueOf(CargoSelect), jTextFieldLogin.getText(), jPasswordFieldSenha.getText());
           
           int idvalida = Integer.parseInt(jLabelID.getText());
            
                   fachada.alterarUsuario(idvalida,jTextFieldLogin.getText(), jPasswordFieldSenha.getText());
                   JOptionPane.showMessageDialog(null, "Concluído com Sucesso!","Mensagem",0);
                   
                   ArrayList<Usuario> lista = fachada.listarUsuario();
    
    String[] colunas = {"id","login","senha"};        
    
    Object[][] dados = carregarDados(lista);        
    
    DefaultTableModel model = new DefaultTableModel(dados, colunas);        
            
    jTable1.setModel(model);
    
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
     jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
     jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
     //jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);
     jTable1.setRowSelectionInterval(0, 0);
     
     
      jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
                   
                   
        } 
       catch(BancoDeDadosException ex){
           JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
       }
          jTextFieldLogin.setText("");
           jPasswordFieldSenha.setText("");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        jLabelID.setText((jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString());

        try {

            Usuario ler = fachada.lerUsuario(jLabelID.getText());

            //jTextFieldLogin.setText(ler.getLogin());
            //jPasswordFieldSenha.setText (Integer.toString(ler.getSenha()));
            // jPasswordFieldSenha.setText(ler.getSenha());
            //jTextFielQuant.setText(Integer.toString(ler.getQuantidade()));
        }
        catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                ex.getMessage(), "Erro",
                JOptionPane.ERROR_MESSAGE);
        }

        try{

            //fachada.adicionarUsuarios(jTextFieldCadastroRH.getText(), jTextFieldNome.getText(), jTextFieldCPF.getText(), jTextFieldDataNascimento.getText(), jTextFieldSetor.getText(), String.valueOf(CargoSelect), jTextFieldLogin.getText(), jPasswordFieldSenha.getText());

            int idvalida = Integer.parseInt(jLabelID.getText());

            fachada.deletarUsuario(idvalida);
            JOptionPane.showMessageDialog(null, "Concluído com Sucesso!","Mensagem",0);

            ArrayList<Usuario> lista = fachada.listarUsuario();

            String[] colunas = {"id","login","senha"};

            Object[][] dados = carregarDados(lista);

            DefaultTableModel model = new DefaultTableModel(dados, colunas);

            jTable1.setModel(model);

            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            //jTable1.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable1.setRowSelectionInterval(0, 0);

            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

        }
        catch(BancoDeDadosException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
        }
        jTextFieldLogin.setText("");
        jPasswordFieldSenha.setText("");
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                new listarUsuario().setVisible(true);
            } catch (LoginExistenteException ex) {
                    Logger.getLogger(listarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
