/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import excecoes.BancoDeDadosException;
import excecoes.NomeNuloException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import negocio.Fachada;
import negocio.entidades.Cliente;
import negocio.entidades.Venda;

/**
 *
 * @author DEYVISON
 */
public class Listagemvenda extends javax.swing.JFrame {
 private Fachada fachada;
    /**
     * Creates new form listap
     */
    public Listagemvenda() throws NomeNuloException {
        initComponents();
        fachada = new Fachada();
        try{
    ArrayList<Venda> lista = fachada.listarVenda();
    
    String[] colunas = {"id","data","nomeCliente","nomeProduto","valorVenda","quant"};        
    
    Object[][] dados = carregarDados(lista);        
    
    DefaultTableModel model = new DefaultTableModel(dados, colunas);        
            
    jTable1.setModel(model);
    
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
     jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
     jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
     jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
     //jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
     //jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
     
     jTable1.setRowSelectionInterval(0, 0);
     
     
      jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
    } catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
     }
      
         }
      
    // private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {
      //   setVisible(false);
     //}
         private Object[][] carregarDados(ArrayList<Venda> lista) {
                 Object[][] dados = new Object[lista.size()][6];
         
        for (int i = 0; i < lista.size(); i++) {
            dados[i][0] = lista.get(i).getId();
            dados[i][1] = lista.get(i).getData();
           dados[i][2] = lista.get(i).getNomeCliente();
            dados[i][3] = lista.get(i).getNomeProduto();
            dados[i][4] = lista.get(i).getValorVenda();
           dados[i][5] = lista.get(i).getQuant();
           // dados[i][6] = lista.get(i).getCep();
           // dados[i][7] = lista.get(i).getBairro();
           
        }
         return dados;
    
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Vendas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("RELATORIO DE VENDAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(586, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagemvenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagemvenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagemvenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagemvenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Listagemvenda().setVisible(true);
                } catch (NomeNuloException ex) {
                    Logger.getLogger(Listagemvenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
