/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import negocio.Fachada;
import excecoes.BancoDeDadosException;
import excecoes.NomeNuloException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import negocio.Fachada;
import negocio.entidades.Cliente;
/**
 *
 * @author Klevson
 */
public class listarCliente extends javax.swing.JFrame {
 private Fachada fachada;
    /**
     * Creates new form listarCliente
     */
    public listarCliente() throws NomeNuloException {
        initComponents();
    fachada = new Fachada();
    
            
    try{
    ArrayList<Cliente> lista = fachada.listarCliente();
    
    String[] colunas = {"cliente_id","nome","cpf","telefone","endereco","numero","cep","bairro"};        
    
    Object[][] dados = carregarDados(lista);        
    
    DefaultTableModel model = new DefaultTableModel(dados, colunas);        
            
    jTable1.setModel(model);
    
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
     jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
     jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
     jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
     
     jTable1.setRowSelectionInterval(0, 0);
     
     
      jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
    } catch (BancoDeDadosException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
     }
      
         }
      
    // private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {
      //   setVisible(false);
     //}
         private Object[][] carregarDados(ArrayList<Cliente> lista) {
                 Object[][] dados = new Object[lista.size()][8];
         
        for (int i = 0; i < lista.size(); i++) {
            dados[i][0] = lista.get(i).getCliente_id();
            dados[i][1] = lista.get(i).getNome();
            dados[i][2] = lista.get(i).getCpf();
            dados[i][3] = lista.get(i).getTelefone();
            dados[i][4] = lista.get(i).getEndereco();
            dados[i][5] = lista.get(i).getNumero();
            dados[i][6] = lista.get(i).getCidade();
            dados[i][7] = lista.get(i).getBairro();
           
        }
         return dados;
    
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextNumero = new javax.swing.JTextField();
        jTextCpf = new javax.swing.JTextField();
        jTextCep = new javax.swing.JTextField();
        jTextBairro = new javax.swing.JTextField();
        jTextEndereco = new javax.swing.JTextField();
        jTextTelefone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Cliente");

        jLabelID.setText("Id:");

        jLabel2.setText("Cep:");

        jLabel3.setText("Cpf:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Numero:");

        jLabel7.setText("Nome:");

        jLabel8.setText("Endereço:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelID)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addGap(112, 112, 112))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelID)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonDeletar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        setSize(new java.awt.Dimension(706, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

int idvalida = Integer.parseInt(jLabelID.getText());
                  
     try {
         fachada.EditarCliente(idvalida, jTextNome.getText(),jTextCpf.getText(),jTextTelefone.getText(),jTextEndereco.getText(),jTextNumero.getText(),jTextCep.getText(),jTextBairro.getText());
         ArrayList<Cliente> lista = fachada.listarCliente();
    
    String[] colunas = {"id","nome","cpf","telefone","endereco","numero","cep","bairro"};        
    
    Object[][] dados = carregarDados(lista);        
    
    DefaultTableModel model = new DefaultTableModel(dados, colunas);        
            
    jTable1.setModel(model);
    
     jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
     jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
     jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
     jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
     jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
     
     
     
     jTable1.setRowSelectionInterval(0, 0);
     
     
      jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
     
} catch (NomeNuloException ex) {
         Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
     } catch (BancoDeDadosException ex) {
         Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
     }
                JOptionPane.showMessageDialog(null, "Concluído com Sucesso!","Mensagem",0);
              











        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
jLabelID.setText((jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString());
        try{
              try {
            
            Cliente ler = fachada.lerCliente(jLabelID.getText());
            jTextNome.setText(ler.getNome());
            jTextCpf.setText(ler.getCpf());
            jTextTelefone.setText(ler.getTelefone());
            jTextEndereco.setText(ler.getEndereco());
            jTextNumero.setText(ler.getNumero());
            jTextCep.setText(ler.getCidade());
            jTextBairro.setText(ler.getBairro());

    } catch (BancoDeDadosException ex) {
        Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
    } }catch (NomeNuloException ex) {
        Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_jButtonEditarActionPerformed
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setVisible(false);    
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed

        jLabelID.setText((jTable1.getValueAt(jTable1.getSelectedRow(),0)).toString());
        try{
            try {

                Cliente ler = fachada.lerCliente(jLabelID.getText());

            } catch (BancoDeDadosException ex) {
                Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
            } }catch (NomeNuloException ex) {
                Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }

            int idvalida = Integer.parseInt(jLabelID.getText());

            try {
                fachada.deletarCliente(idvalida);
                ArrayList<Cliente> lista = fachada.listarCliente();

                String[] colunas = {"id","nome","cpf","telefone","endereco","numero","cep","bairro"};

                Object[][] dados = carregarDados(lista);

                DefaultTableModel model = new DefaultTableModel(dados, colunas);

                jTable1.setModel(model);

                jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
                jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
                jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
                jTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
                jTable1.getColumnModel().getColumn(4).setPreferredWidth(200);
                jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
                jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
                jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);

                jTable1.setRowSelectionInterval(0, 0);

                jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);

            } catch (NomeNuloException ex) {
                Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BancoDeDadosException ex) {
                Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Concluído com Sucesso!","Mensagem",0);

    }//GEN-LAST:event_jButtonDeletarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new listarCliente().setVisible(true);
                } catch (NomeNuloException ex) {
                    Logger.getLogger(listarCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextBairro;
    private javax.swing.JTextField jTextCep;
    private javax.swing.JTextField jTextCpf;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextTelefone;
    // End of variables declaration//GEN-END:variables
}
